
<?php 
	header("Content-Type: text/xml");
	if(isset($_GET['type'])): ?>
<?php if($_GET['type'] == "base"): ?>
<List>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>Parts</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>2</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of basic building parts built by Roblox</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>2</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21008218</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>base</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>Models</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>3</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of simple models created by Roblox</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>3</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21008416</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>base</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>Gameplay</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>4</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of simple gameplay objects created by Roblox</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>4</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21008449</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>base</Value>
			</Entry>
		</Table>
	</Value>
</List>
<?php elseif($_GET['type'] == "user"): ?>
<List>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>My Models</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>-8</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of my models.</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>-8</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21267705</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>private</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>My Decals</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>-7</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of my decals.</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>-7</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21002577</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>private</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>XD Decal Set</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>60856</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A collection of decals to decorate your skate park</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>60856</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>23154282</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>user</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>XD Skate Park Set</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>60855</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A collection of skate park objects</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>60855</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>23154260</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>user</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>Gameplay</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>4</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of simple gameplay objects created by Roblox</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>4</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21008449</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>user</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>Models</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>3</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of simple models created by Roblox</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>3</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21008416</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>user</Value>
			</Entry>
		</Table>
	</Value>
	<Value>
		<Table>
			<Entry>
				<Key>Name</Key>
				<Value>Parts</Value>
			</Entry>
			<Entry>
				<Key>CategoryId</Key>
				<Value>2</Value>
			</Entry>
			<Entry>
				<Key>Description</Key>
				<Value>A set of basic building parts built by Roblox</Value>
			</Entry>
			<Entry>
				<Key>AssetSetId</Key>
				<Value>2</Value>
			</Entry>
			<Entry>
				<Key>CreatorName</Key>
				<Value>Roblox</Value>
			</Entry>
			<Entry>
				<Key>ImageAssetId</Key>
				<Value>21008218</Value>
			</Entry>
			<Entry>
				<Key>SetType</Key>
				<Value>user</Value>
			</Entry>
		</Table>
	</Value>
</List>
<?php endif ?>
<?php else: ?>
<?php if(isset($_GET['sid'])): ?>
<List><Value><Table><Entry><Key>Name</Key><Value>Zeke and Luther Diagonal Logo</Value></Entry><Entry><Key>AssetId</Key><Value>23155714</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719346</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Zeke and Luther Rectangular Logo</Value></Entry><Entry><Key>AssetId</Key><Value>23155694</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719302</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Zeke and Luther Square Logo</Value></Entry><Entry><Key>AssetId</Key><Value>23155676</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719244</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Stopwatch</Value></Entry><Entry><Key>AssetId</Key><Value>23155963</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719905</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Stamp</Value></Entry><Entry><Key>AssetId</Key><Value>23155967</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719912</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Graffiti</Value></Entry><Entry><Key>AssetId</Key><Value>23155948</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719877</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Flame</Value></Entry><Entry><Key>AssetId</Key><Value>23155945</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719872</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Birds</Value></Entry><Entry><Key>AssetId</Key><Value>23155912</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719810</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Bling</Value></Entry><Entry><Key>AssetId</Key><Value>23155918</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719825</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Boombox</Value></Entry><Entry><Key>AssetId</Key><Value>23155929</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719841</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Filmstrip</Value></Entry><Entry><Key>AssetId</Key><Value>23155938</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719858</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Biketrack</Value></Entry><Entry><Key>AssetId</Key><Value>23155908</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719798</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Android</Value></Entry><Entry><Key>AssetId</Key><Value>23155904</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719791</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Zeke Action 1</Value></Entry><Entry><Key>AssetId</Key><Value>23155839</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719651</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Lava</Value></Entry><Entry><Key>AssetId</Key><Value>23155957</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719890</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Dots</Value></Entry><Entry><Key>AssetId</Key><Value>23155932</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719848</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Luther Action 2</Value></Entry><Entry><Key>AssetId</Key><Value>23155833</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719640</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Luther Action 1</Value></Entry><Entry><Key>AssetId</Key><Value>23155830</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719631</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>XD Controller</Value></Entry><Entry><Key>AssetId</Key><Value>23156313</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57720858</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Zeke Action 3</Value></Entry><Entry><Key>AssetId</Key><Value>23155847</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719669</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>Zeke Action 2</Value></Entry><Entry><Key>AssetId</Key><Value>23155842</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>57719658</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>cement</Value></Entry><Entry><Key>AssetId</Key><Value>67993072</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>162675734</Value></Entry><Entry><Key>CreatorName</Key><Value>Roblox</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value><Value><Table><Entry><Key>Name</Key><Value>A Skyscraper (unanchored)</Value></Entry><Entry><Key>AssetId</Key><Value>4504502</Value></Entry><Entry><Key>AssetSetId</Key><Value>60856</Value></Entry><Entry><Key>AssetVersionId</Key><Value>9432363</Value></Entry><Entry><Key>CreatorName</Key><Value>Hyrule73</Value></Entry><Entry><Key>IsTrusted</Key><Value>True</Value></Entry></Table></Value></List>
<?php endif ?>
<?php endif ?>